---
- name: Install httpd
  yum:
    name: httpd
    state: present

- name: delete file
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: Configuration httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd_systemd

- name: Configuration 00-mpm.conf
  template:
    src: 00-mpm.conf.j2
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd_systemd

- name: Start service
  systemd:
    name: httpd.service
    state: started
    enabled: yes
